### ISSUE TITLE
01 - Home Page

### ISSUE THREAD

**Issue by jecaps** [jecaps/Capstone-Project#1]
## Value Statement
As a user
I need a header with a search button and a favorites button 
so that I can search for and save recipes I like.

## Description (Text, Scribble, Wireframe, Design)
![header](https://user-images.githubusercontent.com/76426580/197213392-25080729-4ca7-4816-aebe-13e62e7a4d6e.png)

## Acceptance criteria
- [ ] there should be a header
- [ ] inside a header should be a logo, a search button, and a favorites button
- [ ] the logo, search button, and favorites button should be displayed in a row

## Tasks
- [ ] install react
- [ ] remove default data
- [ ] add header element
- [ ] add search icon
- [ ] add logo
- [ ] add a heart or star button for liked items

## Size
small
