### ISSUE TITLE
04 - Home Page

### ISSUE THREAD

**Issue by jecaps** [jecaps/Capstone-Project#3]
## Value statement - a requirement, not a solution
As a **user**
I need **a Home Page where there's a list of recipes**
so that **I get an idea of what to cook in the next few days** 

## Description
![Home Page](https://user-images.githubusercontent.com/76426580/197223950-5cb6f8f2-93ae-4ca6-afb9-7e1af392f889.png)

## Definition of done
- [ ] there should be recipe cards
- [ ] the cards should have an image, a favorite button/icon, a recipe name, duration, and a short description
- [ ] there should be a "Recipes you might like" text at the top of the cards list

## Tasks
- [ ] use h2 for the text on the top
- [ ] create dummy data for recipes
- [ ] create Card Component
- [ ] import Card Component to the main file
- [ ] add the main element and ul element inside it
- [ ] map dummy data to create a card for each recipe and insert it into the ul element
- [ ] pass key, image, name, duration, and description as props to the Card Component
- [ ] use article element for the card container
- [ ] use h3 for recipe name
- [ ] use p for other texts
- [ ] use a button element for the favorite icon
- [ ] card container should have a position relative
- [ ] favorite icon should have a position absolute

## Size
medium

**Comment by sebsch1337** [comment]
Looks good - very detailed! :) Just two little things:
- The third acceptance criteria, what exactly is the text for? Maybe you could specify it a bit more.
- What kind of element is the fav icon and when do you add it?

**Comment by jecaps** [comment]
Oh, thank you for your remarks. I also noticed just now that the third acceptance criteria was a bit vague. I should have added the "Recipes you might like" text. 😄 And the fave icon will be a button element. 😁

**Comment by sebsch1337** [comment]
LGTM :)

**Comment by Kheirah** [comment]
Very good start!
@sebsch1337 had a point with the fav icon. The button itself is a great idea. But you should add the button when you implement its functionality too. Imagine the user sees the fav icon, clicks it, and nothing happens. Only add that which is immediately useful to the user. 
Create a separate little user story for the fav button and add its functionality. 👍😄
