### ISSUE TITLE
04 - Favorite Button

### ISSUE THREAD

**Issue by jecaps** [jecaps/Capstone-Project#4]
## Value statement
As a user
I need the favorite icon to change color on click/press
so that I can recognize which recipes I  already liked 

## Description
<img width="483" alt="favorite-button" src="https://user-images.githubusercontent.com/76426580/197352561-aee3fb3e-714c-4956-b69b-4d85362f8ae1.png">

## Acceptance criteria
- [ ] button should change color on click

## Tasks
- [ ] In the main js file (App.js), pass the state setter as props to the Card Component
- [ ] create function that toggles value of the "favorite" key in the recipe object in the Card Component
- [ ] update the state that holds the dummy data 

## Size
small

**Comment by philmetscher** [comment]
Hey :) Nice short user-story 👍 
However, for **Value statement** I would write something more like:
`As a user, I would like the Favorite icon to turn red when I've clicked it, so I can see what i have already liked`

**Acceptance criteria**
update color of `Icon component` to  red when clicked

Tasks:
Task 1: describe a little bit more how the state is stored

Task 2: I would write:
- [ ] add a `Icon component` in the top-right corner of the `Card component`
  - [ ] add a function for the `Icon component` which updates the cards states (or something like that)

**Comment by jecaps** [comment]
Hey, thanks for your suggestions. I have updated the value statement but I haven't decided on the colors yet, so I did not specify any. 

Regarding the proposed icon component, I'd like to stick to a button, as this button is only used in the Card Component.
