### ISSUE TITLE
06 - Favorites Page

### ISSUE THREAD

**Issue by jecaps** [jecaps/Capstone-Project#5]
## Value statement
As a **user**
I need **a favorites page** 
to **see all the recipes I liked** 

## Description 
<img width="402" alt="Favorites Page" src="https://user-images.githubusercontent.com/76426580/197357135-28f6cfa6-537d-4db7-86c9-eec70f29a95a.png">

## Definition of Done
- [ ] there should be a "Your Favorites" text above the cards list to make the user aware that he/she is not on the home page
- [ ] only cards that are liked should be shown on this page

## Tasks
- [ ] create a `pages` folder and add a `Favorites.js` file in it
- [ ] import the `Favorites` Component from `pages/Favorites.js` to `App.js` 
- [ ] pass the state of the dummy data as props to the `Favorites` Component 
- [ ] use h2 for the text on the top
- [ ] import the Card Component created in #3 in `Favorites.js`
- [ ] filter state of the dummy data only returning recipes that were liked, then map on the state that was passed from App.js. 
- [ ] pass key, image, name, duration, and description of the filtered objects as props to the Card Component, 

## Size
small

**Comment by philmetscher** [comment]
personal re-write editon nr. 2 😉 
**Tasks**
Task 1: i think the `pages` folder already exists at the very beginning of your project
I would write
"create a new page `/pages/favorites.js`"

Task 2: Can you describe what the `Favorites component` is? Do you mean the page?

Task 3: which state? 😉 

Task 5: which file?

Task 6: which state again 😉 

Task 7: where are these props are coming from?
