### ISSUE TITLE
06 - Search Bar 

### ISSUE THREAD

**Issue by jecaps** [jecaps/Capstone-Project#6]
## Value statement
As a **user** 
I need **a search bar** 
so that **I can look for recipes I want to cook on a certain day** 

## Description 

<img width="781" alt="Screenshot 2022-10-23 at 19 58 22" src="https://user-images.githubusercontent.com/76426580/197408011-55ac4403-09f7-4330-a225-a852a4b15ae2.png">

## Definition of Done
- [ ] search bar should expand when clicked
- [ ] there are recipe suggestions appearing once the user starts typing on the search bar
- [ ] there is a cancel button so the user can cancel searching

## Tasks
- [ ] create an input field for searching
- [ ] create a function that expands the search bar when the search button is clicked
- [ ] install and import fuzzy search
- [ ] add cancel button 
- [ ] create a function that closes the search bar when the cancel button is clicked
- [ ] make suggestion texts appear when there are characters inside the search field

## Size
medium

**Comment by philmetscher** [comment]
personal re-write editon nr. 3 😉 
**Value statement** - Typo: `I need a search bar`

**Tasks**
- [ ] create a `Search Bar component`
  - [ ] with an input-field
  - [ ] and a`Button component` (hide)
    - [ ] add a function to hide the `Search Bar component`
- [ ] add a function to the `Icon component` (zoom) to show the `Search Bar component`

**Comment by jecaps** [comment]
Hello and thank you once again for your insights. Good point, I agree a `Search Bar` Component would make sense here since I also have to use it in another part of the code. As for the button, I would not create a separate component for that since I am only using it within this component. 😬
