### ISSUE TITLE
07 - Recipe Details

### ISSUE THREAD

**Issue by jecaps** [jecaps/Capstone-Project#7]
## Value statement
As a **user** 
I would like to **be directed to a recipes detail page when I click on a recipe card or a suggested item from the search results**
where **I see the ingredients and the instructions for the recipe** 

## Description 

![Recipe Details](https://user-images.githubusercontent.com/76426580/197548956-48eb8a58-47b2-4508-a57c-51b2f72d3fdb.png)

## Definition of Done
- [ ] there should be the image, name, duration, servings, description, ingredients, and instructions of the recipe
- [ ] there should be the `Add to Plan`(should not work for now) and the `Add to Favorites` buttons

## Tasks
- [ ] create a `RecipeDetails` page
- [ ] display the image, name, duration, servings, description, ingredients, and instructions of the recipe
- [ ] create an `Add to Plan` button and an `Add To Favorites` button 

## Size
small
